### PR TITLE
Fixui2

### PR DESCRIPTION
**Pull request by atsastry**

### CODE REVIEW

**Review by dleiferives — APPROVED** [review]
Will need review, will approve for presentation.

**Comment by TeachMeTW** [comment]
@dleiferives  @patturtestsite  @atsastry No need for this; fix already added -- see main and run locally

**Comment by TeachMeTW** [comment]
No need to rebuild; just do `docker-compose up`

**Comment by TeachMeTW** [comment]
after switching to main via `git checkout main` and doing `git pull origin`

**Pull request closed without merging**
